### ISSUE TITLE
Stop behaviour is not working

### ISSUE THREAD

**Issue by uri** [HealthWave/tin-can#4]
Currently a service implementing this gem will have to create some kind of wrapper around it to be able to start/stop. In a rails project his might be a rakefile. However once the process is started you cannot use ruby to stop it. The current implementation does not work:

```ruby
  def self.stop
    TinCan::EventHandler.stop
  end
```

This is because the event handler that is already running is in a different process. Calling stop, even in a static scope will not retrieve the currently running handler.

This `::stop` method needs to be more generic and use system calls.

```ruby
def self.stop working_dir
  sh "kill -9 $(#{working_dir}/tmp/pids/tin_can.pid)"
end
```

And then for example invoked within a rails project using a rakefile:

```ruby
task stop: :environment do
  TinCan.stop Rails.root
end
```

**Comment by parruda** [comment]
Fixed with the new version
